import React from "react";
import Navb from "./Navb";
import './Home.css'
import im1 from './assets/img2.jpg';
import im2 from './assets/img1.jpeg';
import im3 from './assets/risk.jpg';
import img from './assets/img.jpeg';
import imx from './assets/star.png';
import Footer from "./Footer";
import Marquee from "./Marquee";


const Home = () => {
  return (
    <div >
      <Navb/>
      <Marquee/>
      <div style={{display:'flex', marginTop:'20px'}} className="container">
        <div style={{marginLeft: '10px', marginRight:'10px'}}>
        <h1 style={{fontSize:'36px'}}>Income Risk: What It Means, How It Works</h1>
        <h1><b>What Is Income Risk?</b></h1>
        <p style={{fontSize:'20px', textWrap:'wrap', lineHeight:'2'}}>Income risk is the risk that the income stream paid
        by a fund will decrease in response to a drop in interest rates. This
        risk is most prevalent in the money market and other short-term income
        fund strategies (versus longer-term strategies that lock in interest
        rates). Income risk is an extension of the interest-rate risk on an
        individual bond.
      </p></div>
      <img className="img" src={im1} alt="Logo" style={{height:'400px', width:'700px',marginRight:'20px', borderRadius:'15px'}}/>
      </div>

      <div style={{display:'flex', marginTop:'40px'}}>
        <div style={{marginLeft: '10px', marginRight:'10px'}}>
        <img className="img" src={im2} alt="Logo" style={{height:'400px', width:'700px',marginRight:'20px', borderRadius:'15px', marginTop:'65px'}}/>
        </div>
        <div>
          <h2 id="key"><img src={imx} style={{height:'25px', width:'25px',marginRight:'5px'}}/>
            &nbsp;Key Takeaways</h2>
      <ul style={{fontSize:'20px',marginRight:'50px'}}>
        <li>Income risk is the risk that the yield of a fund investing
        in short-term debt securities will decrease because of a decline in
        interest rates.</li>
        <li>This risk is most prevalent in the money market and
        other short-term income fund strategies.</li>
        <li>The fluctuation of interest
        rates can often have a significant effect on the performance of various
        investments held by a short-term investment fund; this increases the
        degree of income risk for that fund because the income generated by the
        fund is continually reinvested at the current rate.</li>
      </ul>
        </div>
      </div>  
      
      <div style={{display:'flex', marginTop:'40px'}}>
        <div style={{marginLeft: '10px', marginRight:'10px'}}>
        <h2 id="key1"><img src={imx} style={{height:'30px', width:'30px',marginRight:'5px'}}/><b>&nbsp;Understanding Income Risk</b></h2>
        <ul style={{fontSize:'20px',marginRight:'50px'}}>
        <li>Income risk is the risk that the yield of a fund investing in short-term debt securities will decrease because of a decline in interest rates.</li>
        <li>The fluctuation of interest rates can often have a significant effect on the performance of various investments held by a short-term investment fund; this increases the degree of income risk for that fund. This is because the income generated by the fund is continually reinvested at the current rate.</li>
        <li>For example, consider a mutual fund that invests in money market securities with maturities of less than a year. If interest rates decline, then the yield on the money market fund will also decline: when the money market securities mature, the returns are reinvested at lower interest rates. Income risk is the same concept as interest-rate risk, but the income risk applies to funds, while the interest-rate risk applies to individual debt securities.
        The interest rates used to calculate the payout from a money market fund are typically a little less than the prevailing rate. This means that if the current interest rate is 4%, the money market may base income disbursements on a rate of 3.75%. Should the current interest rate dip to 3%, then the money market will adjust accordingly, shifting the rate used to determine income payouts to 2.75%.
        </li>
        </ul>
        </div>
        <div>
        <img className="img" src={im3} alt="Logo" style={{height:'500px', width:'700px',marginRight:'20px', borderRadius:'15px', marginTop:'120px'}}/>
        </div>
      </div>

        <div style={{display:'flex', marginTop:'40px'}}>
        <div style={{marginLeft: '10px', marginRight:'10px'}}>
        <img className="img" src={img} alt="Logo" style={{height:'400px', width:'700px',marginRight:'20px', borderRadius:'15px',marginTop:'70px'}}/>
        </div>
        <div>
        <h2 id="key"><img src={imx} style={{height:'30px', width:'30px',marginRight:'5px'}}/>&nbsp;Minimizing Income Risk</h2>
      <ul style={{fontSize:'20px',marginRight:'50px'}}>
      <li>One strategy for minimizing the degree of income risk associated with a portfolio is to diversify the assets so that long-term investments with fixed rates of interest are balanced with short-term income fund holdings.</li> 
      <li>Doing so creates a situation in which the fixed rates on the long-term investments offset any decreases in income that may occur when interest rates drop.</li> 
      <li>This helps to establish a more consistent floor for income payouts, allowing beneficiaries to arrange their budgets based on that minimum.</li>
      </ul>
        </div>
      </div> 
      
      {/* Footer  */}
      <Footer/>
    </div>
  );
};

export default Home;
